name: Assign Issues
on:
  issues:
    types: [opened]

jobs:
  assign_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: andymckay/assign@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: Ogieriakhi17
